name: Auto-Update Game Scripts

# Controls when the workflow will run
on:
  schedule:
    - cron:  '0 0 * * 0' 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          chmod u+x ./.github/workflows/update.sh
          ./.github/workflows/update.sh
      - uses: EndBug/add-and-commit@v9
        with:
          message: Auto-update scripts
          default_author: github_actions
